/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
  BaseContract,
  ContractTransaction,
  PayableOverrides,
  CallOverrides,
} from "ethers";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";
import type { TypedEventFilter, TypedEvent, TypedListener } from "./common";

interface GenericBridgeFacetInterface extends ethers.utils.Interface {
  functions: {
    "startBridgeTokensGeneric((bytes32,string,address,address,address,address,uint256,uint256),(uint256,address,address,bytes))": FunctionFragment;
    "swapAndStartBridgeTokensGeneric((bytes32,string,address,address,address,address,uint256,uint256),tuple[],(uint256,address,address,bytes))": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "startBridgeTokensGeneric",
    values: [
      {
        transactionId: BytesLike;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        destinationChainId: BigNumberish;
        amount: BigNumberish;
      },
      {
        amount: BigNumberish;
        assetId: string;
        callTo: string;
        callData: BytesLike;
      }
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "swapAndStartBridgeTokensGeneric",
    values: [
      {
        transactionId: BytesLike;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        destinationChainId: BigNumberish;
        amount: BigNumberish;
      },
      {
        callTo: string;
        approveTo: string;
        sendingAssetId: string;
        receivingAssetId: string;
        fromAmount: BigNumberish;
        callData: BytesLike;
      }[],
      {
        amount: BigNumberish;
        assetId: string;
        callTo: string;
        callData: BytesLike;
      }
    ]
  ): string;

  decodeFunctionResult(
    functionFragment: "startBridgeTokensGeneric",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapAndStartBridgeTokensGeneric",
    data: BytesLike
  ): Result;

  events: {
    "Inited(address,uint64)": EventFragment;
    "FenixTransferCompleted(bytes32,address,address,uint256,uint256)": EventFragment;
    "FenixTransferConfirmed(bytes32,string,address,address,address,address,uint256,uint256,uint256)": EventFragment;
    "FenixTransferRefunded(bytes32,string,address,address,address,address,uint256,uint256,uint256)": EventFragment;
    "FenixTransferStarted(bytes32,string,address,address,address,address,uint256,uint256,uint256)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "Inited"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FenixTransferCompleted"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FenixTransferConfirmed"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FenixTransferRefunded"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "FenixTransferStarted"): EventFragment;
}

export type InitedEvent = TypedEvent<
  [string, BigNumber] & { bridge: string; chainId: BigNumber }
>;

export type FenixTransferCompletedEvent = TypedEvent<
  [string, string, string, BigNumber, BigNumber] & {
    transactionId: string;
    receivingAssetId: string;
    receiver: string;
    amount: BigNumber;
    timestamp: BigNumber;
  }
>;

export type FenixTransferConfirmedEvent = TypedEvent<
  [
    string,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    transactionId: string;
    integrator: string;
    referrer: string;
    sendingAssetId: string;
    receivingAssetId: string;
    receiver: string;
    amount: BigNumber;
    destinationChainId: BigNumber;
    timestamp: BigNumber;
  }
>;

export type FenixTransferRefundedEvent = TypedEvent<
  [
    string,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    transactionId: string;
    integrator: string;
    referrer: string;
    sendingAssetId: string;
    receivingAssetId: string;
    receiver: string;
    amount: BigNumber;
    destinationChainId: BigNumber;
    timestamp: BigNumber;
  }
>;

export type FenixTransferStartedEvent = TypedEvent<
  [
    string,
    string,
    string,
    string,
    string,
    string,
    BigNumber,
    BigNumber,
    BigNumber
  ] & {
    transactionId: string;
    integrator: string;
    referrer: string;
    sendingAssetId: string;
    receivingAssetId: string;
    receiver: string;
    amount: BigNumber;
    destinationChainId: BigNumber;
    timestamp: BigNumber;
  }
>;

export class GenericBridgeFacet extends BaseContract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  listeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter?: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): Array<TypedListener<EventArgsArray, EventArgsObject>>;
  off<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  on<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  once<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeListener<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>,
    listener: TypedListener<EventArgsArray, EventArgsObject>
  ): this;
  removeAllListeners<EventArgsArray extends Array<any>, EventArgsObject>(
    eventFilter: TypedEventFilter<EventArgsArray, EventArgsObject>
  ): this;

  listeners(eventName?: string): Array<Listener>;
  off(eventName: string, listener: Listener): this;
  on(eventName: string, listener: Listener): this;
  once(eventName: string, listener: Listener): this;
  removeListener(eventName: string, listener: Listener): this;
  removeAllListeners(eventName?: string): this;

  queryFilter<EventArgsArray extends Array<any>, EventArgsObject>(
    event: TypedEventFilter<EventArgsArray, EventArgsObject>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEvent<EventArgsArray & EventArgsObject>>>;

  interface: GenericBridgeFacetInterface;

  functions: {
    startBridgeTokensGeneric(
      _fenixData: {
        transactionId: BytesLike;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        destinationChainId: BigNumberish;
        amount: BigNumberish;
      },
      _bridgeData: {
        amount: BigNumberish;
        assetId: string;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;

    swapAndStartBridgeTokensGeneric(
      _fenixData: {
        transactionId: BytesLike;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        destinationChainId: BigNumberish;
        amount: BigNumberish;
      },
      _swapData: {
        callTo: string;
        approveTo: string;
        sendingAssetId: string;
        receivingAssetId: string;
        fromAmount: BigNumberish;
        callData: BytesLike;
      }[],
      _bridgeData: {
        amount: BigNumberish;
        assetId: string;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<ContractTransaction>;
  };

  startBridgeTokensGeneric(
    _fenixData: {
      transactionId: BytesLike;
      integrator: string;
      referrer: string;
      sendingAssetId: string;
      receivingAssetId: string;
      receiver: string;
      destinationChainId: BigNumberish;
      amount: BigNumberish;
    },
    _bridgeData: {
      amount: BigNumberish;
      assetId: string;
      callTo: string;
      callData: BytesLike;
    },
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  swapAndStartBridgeTokensGeneric(
    _fenixData: {
      transactionId: BytesLike;
      integrator: string;
      referrer: string;
      sendingAssetId: string;
      receivingAssetId: string;
      receiver: string;
      destinationChainId: BigNumberish;
      amount: BigNumberish;
    },
    _swapData: {
      callTo: string;
      approveTo: string;
      sendingAssetId: string;
      receivingAssetId: string;
      fromAmount: BigNumberish;
      callData: BytesLike;
    }[],
    _bridgeData: {
      amount: BigNumberish;
      assetId: string;
      callTo: string;
      callData: BytesLike;
    },
    overrides?: PayableOverrides & { from?: string | Promise<string> }
  ): Promise<ContractTransaction>;

  callStatic: {
    startBridgeTokensGeneric(
      _fenixData: {
        transactionId: BytesLike;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        destinationChainId: BigNumberish;
        amount: BigNumberish;
      },
      _bridgeData: {
        amount: BigNumberish;
        assetId: string;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;

    swapAndStartBridgeTokensGeneric(
      _fenixData: {
        transactionId: BytesLike;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        destinationChainId: BigNumberish;
        amount: BigNumberish;
      },
      _swapData: {
        callTo: string;
        approveTo: string;
        sendingAssetId: string;
        receivingAssetId: string;
        fromAmount: BigNumberish;
        callData: BytesLike;
      }[],
      _bridgeData: {
        amount: BigNumberish;
        assetId: string;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    "Inited(address,uint64)"(
      bridge?: string | null,
      chainId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { bridge: string; chainId: BigNumber }
    >;

    Inited(
      bridge?: string | null,
      chainId?: null
    ): TypedEventFilter<
      [string, BigNumber],
      { bridge: string; chainId: BigNumber }
    >;

    "FenixTransferCompleted(bytes32,address,address,uint256,uint256)"(
      transactionId?: BytesLike | null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      timestamp?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber],
      {
        transactionId: string;
        receivingAssetId: string;
        receiver: string;
        amount: BigNumber;
        timestamp: BigNumber;
      }
    >;

    FenixTransferCompleted(
      transactionId?: BytesLike | null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      timestamp?: null
    ): TypedEventFilter<
      [string, string, string, BigNumber, BigNumber],
      {
        transactionId: string;
        receivingAssetId: string;
        receiver: string;
        amount: BigNumber;
        timestamp: BigNumber;
      }
    >;

    "FenixTransferConfirmed(bytes32,string,address,address,address,address,uint256,uint256,uint256)"(
      transactionId?: BytesLike | null,
      integrator?: null,
      referrer?: null,
      sendingAssetId?: null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      destinationChainId?: null,
      timestamp?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber
      ],
      {
        transactionId: string;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        amount: BigNumber;
        destinationChainId: BigNumber;
        timestamp: BigNumber;
      }
    >;

    FenixTransferConfirmed(
      transactionId?: BytesLike | null,
      integrator?: null,
      referrer?: null,
      sendingAssetId?: null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      destinationChainId?: null,
      timestamp?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber
      ],
      {
        transactionId: string;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        amount: BigNumber;
        destinationChainId: BigNumber;
        timestamp: BigNumber;
      }
    >;

    "FenixTransferRefunded(bytes32,string,address,address,address,address,uint256,uint256,uint256)"(
      transactionId?: BytesLike | null,
      integrator?: null,
      referrer?: null,
      sendingAssetId?: null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      destinationChainId?: null,
      timestamp?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber
      ],
      {
        transactionId: string;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        amount: BigNumber;
        destinationChainId: BigNumber;
        timestamp: BigNumber;
      }
    >;

    FenixTransferRefunded(
      transactionId?: BytesLike | null,
      integrator?: null,
      referrer?: null,
      sendingAssetId?: null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      destinationChainId?: null,
      timestamp?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber
      ],
      {
        transactionId: string;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        amount: BigNumber;
        destinationChainId: BigNumber;
        timestamp: BigNumber;
      }
    >;

    "FenixTransferStarted(bytes32,string,address,address,address,address,uint256,uint256,uint256)"(
      transactionId?: BytesLike | null,
      integrator?: null,
      referrer?: null,
      sendingAssetId?: null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      destinationChainId?: null,
      timestamp?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber
      ],
      {
        transactionId: string;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        amount: BigNumber;
        destinationChainId: BigNumber;
        timestamp: BigNumber;
      }
    >;

    FenixTransferStarted(
      transactionId?: BytesLike | null,
      integrator?: null,
      referrer?: null,
      sendingAssetId?: null,
      receivingAssetId?: null,
      receiver?: null,
      amount?: null,
      destinationChainId?: null,
      timestamp?: null
    ): TypedEventFilter<
      [
        string,
        string,
        string,
        string,
        string,
        string,
        BigNumber,
        BigNumber,
        BigNumber
      ],
      {
        transactionId: string;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        amount: BigNumber;
        destinationChainId: BigNumber;
        timestamp: BigNumber;
      }
    >;
  };

  estimateGas: {
    startBridgeTokensGeneric(
      _fenixData: {
        transactionId: BytesLike;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        destinationChainId: BigNumberish;
        amount: BigNumberish;
      },
      _bridgeData: {
        amount: BigNumberish;
        assetId: string;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;

    swapAndStartBridgeTokensGeneric(
      _fenixData: {
        transactionId: BytesLike;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        destinationChainId: BigNumberish;
        amount: BigNumberish;
      },
      _swapData: {
        callTo: string;
        approveTo: string;
        sendingAssetId: string;
        receivingAssetId: string;
        fromAmount: BigNumberish;
        callData: BytesLike;
      }[],
      _bridgeData: {
        amount: BigNumberish;
        assetId: string;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    startBridgeTokensGeneric(
      _fenixData: {
        transactionId: BytesLike;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        destinationChainId: BigNumberish;
        amount: BigNumberish;
      },
      _bridgeData: {
        amount: BigNumberish;
        assetId: string;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;

    swapAndStartBridgeTokensGeneric(
      _fenixData: {
        transactionId: BytesLike;
        integrator: string;
        referrer: string;
        sendingAssetId: string;
        receivingAssetId: string;
        receiver: string;
        destinationChainId: BigNumberish;
        amount: BigNumberish;
      },
      _swapData: {
        callTo: string;
        approveTo: string;
        sendingAssetId: string;
        receivingAssetId: string;
        fromAmount: BigNumberish;
        callData: BytesLike;
      }[],
      _bridgeData: {
        amount: BigNumberish;
        assetId: string;
        callTo: string;
        callData: BytesLike;
      },
      overrides?: PayableOverrides & { from?: string | Promise<string> }
    ): Promise<PopulatedTransaction>;
  };
}
